services:
  db:
    image: "postgres:${DATABASE_TAG}"
    container_name: "${PROJECT_NAME}-database"
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    ports:
      - "${DATABASE_PORT}:5432"
