# Generated by Django 5.1.1 on 2024-10-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
