# Generated by Django 5.1.2 on 2024-10-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pa_note', '0001_initial'),
        ('pa_tag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='pa_tag.tag'),
        ),
    ]
